# Generated by Django 3.0.7 on 2020-09-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_compras', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
