# Generated by Django 3.0.7 on 2020-09-29 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(blank=True, max_length=400, null=True)),
                ('direccion', models.CharField(blank=True, max_length=400, null=True)),
                ('telefono', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_compra', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_compra', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compra', models.CharField(blank=True, max_length=400, null=True)),
                ('id_insumo', models.CharField(blank=True, max_length=400, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=400, null=True)),
                ('precio', models.CharField(blank=True, max_length=400, null=True)),
                ('subtotal', models.CharField(blank=True, max_length=400, null=True)),
                ('unidad_de_medida', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.CharField(blank=True, max_length=400, null=True)),
                ('id_insumos', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(blank=True, max_length=400, null=True)),
                ('id_pedido', models.CharField(blank=True, max_length=400, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=400, null=True)),
                ('subtotal_producto', models.CharField(blank=True, max_length=400, null=True)),
                ('precio', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produccion', models.CharField(blank=True, max_length=400, null=True)),
                ('id_producto', models.CharField(blank=True, max_length=400, null=True)),
                ('cantidad_detalle', models.CharField(blank=True, max_length=400, null=True)),
                ('cantidad_real_detalle', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos_categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nombre_productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_productos', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(blank=True, max_length=400, null=True)),
                ('estado_pedido', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_pedido', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_entrega', models.CharField(blank=True, max_length=400, null=True)),
                ('cantidad_total', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_detalle_insumo', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_produccion', models.CharField(blank=True, max_length=400, null=True)),
                ('estado_produccion', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_acabado', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nombre_producto', models.CharField(blank=True, max_length=400, null=True)),
                ('id_categoria', models.CharField(blank=True, max_length=400, null=True)),
                ('descripcion_producto', models.CharField(blank=True, max_length=400, null=True)),
                ('cantidad_stock', models.CharField(blank=True, max_length=400, null=True)),
                ('imagen', models.CharField(blank=True, max_length=400, null=True)),
                ('precio', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedidos', models.CharField(blank=True, max_length=400, null=True)),
                ('id_clientes', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_venta', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=400, null=True)),
                ('Cantidad', models.CharField(blank=True, max_length=400, null=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptemplate.Insumos_categoria')),
            ],
        ),
    ]
