# Generated by Django 3.0.7 on 2020-09-29 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptemplate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumos',
            old_name='Cantidad',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='insumos',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='insumos',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
