# Generated by Django 3.0.7 on 2020-09-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptemplate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='total_compras',
            new_name='fecha_compra',
        ),
        migrations.AddField(
            model_name='compras',
            name='total_compra',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
