# Generated by Django 3.0.7 on 2020-10-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptemplate', '0002_auto_20200929_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalles_compras',
            name='unidad_de_medida',
        ),
        migrations.AddField(
            model_name='insumos',
            name='unidad_de_medida',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
