# Generated by Django 3.0.7 on 2020-09-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptemplate', '0002_auto_20200924_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles_compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_insumo', models.CharField(blank=True, max_length=400, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=400, null=True)),
                ('precio', models.CharField(blank=True, max_length=400, null=True)),
                ('subtotal', models.CharField(blank=True, max_length=400, null=True)),
                ('id_compra', models.ManyToManyField(to='apptemplate.Compras')),
            ],
        ),
    ]
