# Generated by Django 3.0.7 on 2020-10-19 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptemplate', '0003_auto_20200930_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='id_categoria',
        ),
        migrations.AddField(
            model_name='nombre_productos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apptemplate.Categoria_productos'),
        ),
    ]
