# Generated by Django 3.0.7 on 2020-09-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptemplate', '0003_detalles_compras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(blank=True, max_length=400, null=True)),
                ('direccion', models.CharField(blank=True, max_length=400, null=True)),
                ('telefono', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.CharField(blank=True, max_length=400, null=True)),
                ('id_insumos', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(blank=True, max_length=400, null=True)),
                ('id_pedido', models.CharField(blank=True, max_length=400, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=400, null=True)),
                ('subtotal_producto', models.CharField(blank=True, max_length=400, null=True)),
                ('precio', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produccion', models.CharField(blank=True, max_length=400, null=True)),
                ('id_producto', models.CharField(blank=True, max_length=400, null=True)),
                ('cantidad_detalle', models.CharField(blank=True, max_length=400, null=True)),
                ('cantidad_real_detalle', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=400, null=True)),
                ('Cantidad', models.CharField(blank=True, max_length=400, null=True)),
                ('Categoria', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nombre_productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_productos', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(blank=True, max_length=400, null=True)),
                ('estado_pedido', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_pedido', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_entrega', models.CharField(blank=True, max_length=400, null=True)),
                ('cantidad_total', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_detalle_insumo', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_produccion', models.CharField(blank=True, max_length=400, null=True)),
                ('estado_produccion', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_acabado', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nombre_producto', models.CharField(blank=True, max_length=400, null=True)),
                ('id_categoria', models.CharField(blank=True, max_length=400, null=True)),
                ('descripcion_producto', models.CharField(blank=True, max_length=400, null=True)),
                ('cantidad_stock', models.CharField(blank=True, max_length=400, null=True)),
                ('imagen', models.CharField(blank=True, max_length=400, null=True)),
                ('precio', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedidos', models.CharField(blank=True, max_length=400, null=True)),
                ('id_clientes', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_venta', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='detalles_compras',
            name='unidad_de_medida',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.RemoveField(
            model_name='detalles_compras',
            name='id_compra',
        ),
        migrations.AddField(
            model_name='detalles_compras',
            name='id_compra',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
