# Generated by Django 3.0.7 on 2020-11-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptemplate', '0004_auto_20201019_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.FileField(default='placeholder.png', null=True, upload_to=''),
        ),
    ]
